name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make run
      run: make run
    - name: build
      run: make 
    - name: Compile Project
      uses: actions/upload-artifact@v4
      with:
        name: compiled_project
        path: mycp
