name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc make
      - name: Build
        run: make mycp
      - name: Compile Project
        uses: actions/upload-artifact@v4
        with:
          name: compiled_project
          path: mycp
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run
      run: make run
  
  
